export const featuredCategories = [
  {
    id: 1,
    name: "Adapter",
    slug: "adapter",
    image: "/images/categories/Adapter.jpeg",
  },
  {
    id: 2,
    name: "Hubs & Docks",
    slug: "hubs-docks",
    image: "/images/categories/Hubs-Docks.jpeg",
  },
  {
    id: 3,
    name: "Wireless Headphone",
    slug: "wireless-headphone",
    image: "/images/categories/Wireless-Headphone.jpeg",
  },
  {
    id: 4,
    name: "Cables",
    slug: "cables",
    image: "/images/categories/Cables.jpeg",
  },
  {
    id: 5,
    name: "Airpods",
    slug: "airpods",
    image: "/images/categories/Airpods.jpeg",
  },
  {
    id: 6,
    name: "Smart Pen",
    slug: "smart-pen",
    image: "/images/categories/Smart-Pen.jpeg",
  },
  {
    id: 7,
    name: "Smart Watch",
    slug: "smart-watch",
    image: "/images/categories/Smart-Watch.jpeg",
  },
  {
    id: 8,
    name: "Home Appliances",
    slug: "home-appliances",
    image: "/images/categories/Home_Appliances.png",
  },
  {
    id: 9,
    name: "Speakers",
    slug: "speakers",
    image: "/images/categories/Speakers.jpeg",
  },
  {
    id: 10,
    name: "Wireless Charger",
    slug: "wireless-charger",
    image: "/images/categories/Wireless-Charger.jpeg",
  },
  {
    id: 11,
    name: "Mobile Phone",
    slug: "mobile-phone",
    image: "/images/categories/Mobile_Phone.jpeg",
  },
  {
    id: 12,
    name: "Headphone",
    slug: "headphone",
    image: "/images/categories/Headphone.jpeg",
  },
  {
    id: 13,
    name: "Laptop",
    slug: "laptop",
    image: "/images/categories/Laptop.jpeg",
  },
  {
    id: 14,
    name: "Tablet Accessories",
    slug: "tablet-accessories",
    image: "/images/categories/Tablet-Accessories.jpeg",
  },
  {
    id: 15,
    name: "Starlink",
    slug: "starlink",
    image: "/images/categories/Starlink.png",
  },
  {
    id: 16,
    name: "Wired Headphone",
    slug: "wired-headphone",
    image: "/images/categories/Wired-Headphone.jpeg",
  },
];
