// lib/cards/cards.ts

export const productsCards = [
  {
    id: 1,
    title: "Galaxy S26 Ultra 5G",
    slug: "galaxy-s26-ultra-5g",
    currentPrice: 114999,
    originalPrice: 119500,
    discountAmount: 4501,
    imageSrc: "/images/cards/Galaxy-S26-Ultra-black-4396.png",
    colors: [
      { name: "Awesome Gray", hex: "#4A4B50" },
      { name: "Awesome Iceblue", hex: "#D2DAE2" },
      { name: "Awesome Lilac", hex: "#A59CC1" },
      { name: "Awesome Navy", hex: "#1B2430" },
    ],
    storage: ["8/128GB", "8/256GB", "12/256GB", "12/512GB"],
    variants: [
      {
        color: "Awesome Gray",
        storage: "8/128GB",
        currentPrice: 112000,
        originalPrice: 115000,
        imageSrc: "/images/cards/Galaxy-S26-Ultra-black-4396.png",
        inStock: true,
        code: "S26G128",
      },
      {
        color: "Awesome Gray",
        storage: "8/256GB",
        currentPrice: 114999,
        originalPrice: 119500,
        imageSrc: "/images/cards/Galaxy-S26-Ultra-black-4396.png",
        inStock: true,
        code: "S26G256",
      },
      {
        color: "Awesome Iceblue",
        storage: "12/256GB",
        currentPrice: 122000,
        originalPrice: 126000,
        imageSrc: "/images/cards/Galaxy-S26-Ultra-black-4396.png",
        inStock: true,
        code: "S26B256",
      },
      {
        color: "Awesome Lilac",
        storage: "12/512GB",
        currentPrice: 130000,
        originalPrice: 135000,
        imageSrc: "/images/cards/Galaxy-S26-Ultra-black-4396.png",
        inStock: true,
        code: "S26L512",
      },
    ],
  },
  {
    id: 2,
    title: "Nothing Phone (4a) Pro",
    slug: "nothing-phone-4a-pro",
    currentPrice: 56000,
    originalPrice: null,
    discountAmount: null,
    imageSrc: "/images/cards/Nothing-Phone-(4a)-Proa-2762.png",
    colors: [
      { name: "Dark Gray", hex: "#2C3E50" },
      { name: "White", hex: "#FFFFFF" },
    ],
    storage: ["8/128GB", "12/256GB"],
    variants: [
      {
        color: "Dark Gray",
        storage: "8/128GB",
        currentPrice: 56000,
        originalPrice: null,
        imageSrc: "/images/cards/Nothing-Phone-(4a)-Proa-2762.png",
        inStock: true,
        code: "NTHG128",
      },
      {
        color: "Dark Gray",
        storage: "12/256GB",
        currentPrice: 62000,
        originalPrice: null,
        imageSrc: "/images/cards/Nothing-Phone-(4a)-Proa-2762.png",
        inStock: true,
        code: "NTHG256",
      },
      {
        color: "White",
        storage: "8/128GB",
        currentPrice: 56500,
        originalPrice: null,
        imageSrc: "/images/cards/Nothing-Phone-(4a)-Proa-2762.png",
        inStock: true,
        code: "NTHW128",
      },
    ],
  },
  {
    id: 3,
    title: "Galaxy A57 5G",
    slug: "galaxy-a57-5g",
    currentPrice: 46000,
    originalPrice: null,
    discountAmount: null,
    imageSrc: "/images/cards/Galaxy-A57-5G-6910.png",
    colors: [
      { name: "Awesome Lilac", hex: "#A59CC1" },
      { name: "Awesome Navy", hex: "#1B2430" },
    ],
    storage: ["8/128GB", "8/256GB"],
    variants: [
      {
        color: "Awesome Lilac",
        storage: "8/128GB",
        currentPrice: 46000,
        originalPrice: null,
        imageSrc: "/images/cards/Galaxy-A57-5G-6910.png",
        inStock: true,
        code: "A57L128",
      },
      {
        color: "Awesome Navy",
        storage: "8/256GB",
        currentPrice: 49500,
        originalPrice: null,
        imageSrc: "/images/cards/Galaxy-A57-5G-6910.png",
        inStock: true,
        code: "A57N256",
      },
    ],
  },
  {
    id: 4,
    title: "Xiaomi Pad 7",
    slug: "xiaomi-pad-7",
    currentPrice: 39500,
    originalPrice: 42000,
    discountAmount: 2500,
    imageSrc: "/images/cards/Xiaomi-Pad-7-blue-6536.jpeg",
    colors: [
      { name: "Cosmic Blue", hex: "#34495E" },
      { name: "Space Gray", hex: "#7F8C8D" },
    ],
    storage: ["6/128GB", "8/256GB"],
    variants: [
      {
        color: "Cosmic Blue",
        storage: "6/128GB",
        currentPrice: 39500,
        originalPrice: 42000,
        imageSrc: "/images/cards/Xiaomi-Pad-7-blue-6536.jpeg",
        inStock: true,
        code: "MIPADB128",
      },
      {
        color: "Space Gray",
        storage: "8/256GB",
        currentPrice: 44000,
        originalPrice: 47000,
        imageSrc: "/images/cards/Xiaomi-Pad-7-blue-6536.jpeg",
        inStock: true,
        code: "MIPADG256",
      },
    ],
  },
  {
    id: 5,
    title: "iPhone 17",
    slug: "iphone-17",
    currentPrice: 100999,
    regularPrice: 102000,
    originalPrice: 102000,
    discountAmount: 1001,
    imageSrc: "/images/cards/iPhone-17-Sage-8941.jpeg",
    colors: [
      { name: "Sage Green", hex: "#99B898" },
      { name: "Black", hex: "#2A2A2A" },
    ],
    storage: ["128GB", "256GB", "512GB"],
    variants: [
      {
        color: "Sage Green",
        storage: "128GB",
        currentPrice: 100999,
        originalPrice: 102000,
        imageSrc: "/images/cards/iPhone-17-Sage-8941.jpeg",
        inStock: true,
        code: "IP17SG128",
      },
      {
        color: "Black",
        storage: "256GB",
        currentPrice: 112000,
        originalPrice: 115000,
        imageSrc: "/images/cards/iPhone-17-Sage-8941.jpeg",
        inStock: true,
        code: "IP17BK256",
      },
    ],
  },
  {
    id: 6,
    title: "Galaxy TAB A11+",
    slug: "galaxy-tab-a11-plus",
    currentPrice: 26500,
    originalPrice: null,
    discountAmount: null,
    imageSrc: "/images/cards/Galaxy-TAB-A11+rge-2585.png",
    colors: [
      { name: "Silver", hex: "#D1D5DB" },
      { name: "Graphite", hex: "#374151" },
    ],
    storage: ["4/64GB", "8/128GB"],
    variants: [
      {
        color: "Silver",
        storage: "4/64GB",
        currentPrice: 26500,
        originalPrice: null,
        imageSrc: "/images/cards/Galaxy-TAB-A11+rge-2585.png",
        inStock: true,
        code: "TABA11S64",
      },
      {
        color: "Graphite",
        storage: "8/128GB",
        currentPrice: 31000,
        originalPrice: null,
        imageSrc: "/images/cards/Galaxy-TAB-A11+rge-2585.png",
        inStock: true,
        code: "TABA11G128",
      },
    ],
  },
  {
    id: 7,
    title: "iPad Air M4 - 2026",
    slug: "ipad-air-m4-2026",
    currentPrice: 73499,
    originalPrice: 88500,
    discountAmount: 15001,
    imageSrc: "/images/cards/iPad-Air-M3---2025a-2380.png",
    colors: [
      { name: "Space Gray", hex: "#7F8C8D" },
      { name: "Starlight", hex: "#F5F5DC" },
    ],
    storage: ["128GB", "256GB"],
    variants: [
      {
        color: "Space Gray",
        storage: "128GB",
        currentPrice: 73499,
        originalPrice: 88500,
        imageSrc: "/images/cards/iPad-Air-M3---2025a-2380.png",
        inStock: true,
        code: "IPADAIRM4G",
      },
      {
        color: "Starlight",
        storage: "256GB",
        currentPrice: 84500,
        originalPrice: 99500,
        imageSrc: "/images/cards/iPad-Air-M3---2025a-2380.png",
        inStock: true,
        code: "IPADAIRM4S",
      },
    ],
  },
  {
    id: 8,
    title: "MacBook Pro M5 Pro 14-Inch 24/1TB 15-Core CPU...",
    slug: "macbook-pro-m5-pro-14-inch-24-1tb-15-core-cpu",
    currentPrice: 277000,
    originalPrice: null,
    discountAmount: null,
    imageSrc:
      "/images/cards/MacBook-Pro-M5-Pro-14-Inch-241TB-18-Core-CPU-20-Core-GPUa-1124.png",
    colors: [
      { name: "Space Black", hex: "#1F2937" },
      { name: "Silver", hex: "#E5E7EB" },
    ],
    storage: ["24GB/1TB", "48GB/2TB"],
    variants: [
      {
        color: "Space Black",
        storage: "24GB/1TB",
        currentPrice: 277000,
        originalPrice: null,
        imageSrc:
          "/images/cards/MacBook-Pro-M5-Pro-14-Inch-241TB-18-Core-CPU-20-Core-GPUa-1124.png",
        inStock: true,
        code: "MBPM5B1TB",
      },
      {
        color: "Silver",
        storage: "48GB/2TB",
        currentPrice: 340000,
        originalPrice: null,
        imageSrc:
          "/images/cards/MacBook-Pro-M5-Pro-14-Inch-241TB-18-Core-CPU-20-Core-GPUa-1124.png",
        inStock: true,
        code: "MBPM5S2TB",
      },
    ],
  },
];
